### ISSUE TITLE
Indicate the NTA boundaries are used reflect those based on 2010 census data

### ISSUE THREAD

**Issue by mtreg** [NYCPlanning/equity-tool#154]
First - nice work on this! What a powerful tool!

To my issue - As a data user, I had to do some quick visual comparison of data to see whether the NTA boundaries reflect the older version, based on 2010 census data, or the more recent one based on 2020 census data. While I realize that distinction could cause some potential confusion if presented on the main landing page or map somehow, having that within the methods and sources or data dictionary would be great.  

Hope this helps and can't wait to explore the data further!

**Comment by TylerMatteo** [comment]
Hey @mtreg! Thank you for this feedback. I can definitely see how that is a little unclear. Just fyi, we recently added a new [contact page](https://equitableexplorer.planning.nyc.gov/contact) where you can submit feedback like this and sign up for a newsletter to hear about new features and data.
